[project]
name = "plugin-com-pot-app-rapid"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10, <3.13"
dependencies = [
    "rapidocr>=2.0.4",
    "requests>=2.32.3",
]


[[tool.uv.index]]
name = "tsinghua-pypi"
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"
default = true
