[project]
name = "plugin-com-pot-app-rapid-py"
version = "1.0.1"
description = "Yet another OCR plugin for pot app"
readme = "README.md"
requires-python = ">=3.10, <3.13"
dependencies = [
    "onnxruntime~=1.21.0",
    "rapidocr~=2.0.6",
    "requests~=2.32.3",
]


[[tool.uv.index]]
name = "tsinghua-pypi"
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"
default = true
